enum AuthErrorCode {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  EXPIRED_REFRESH_TOKEN = "EXPIRED_REFRESH_TOKEN",
  REVOKED_REFRESH_TOKEN = "REVOKED_REFRESH_TOKEN",
  MISSING_ACCESS_TOKEN = "MISSING_ACCESS_TOKEN",
  MISSING_REFRESH_TOKEN = "MISSING_REFRESH_TOKEN",
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
}

export default AuthErrorCode;
