enum AuthErrorCode {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  EXPIRED_REFRESH_TOKEN = "REFRESH_TOKEN_EXPIRED",
  REVOKED_REFRESH_TOKEN = "REFRESH_TOKEN_REVOKED",
  AUTH_TOKEN_MISSING = "AUTH_TOKEN_MISSING",
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
}

export default AuthErrorCode;
