enum ShowErrorCode {
  SHOW_NOT_FOUND = "SHOW_NOT_FOUND",
  SHOW_SEATS_NOT_FOUND = "SHOW_SEATS_NOT_FOUND",
  SEAT_ALREADY_BOOKED = "SEAT_ALREADY_BOOKED",
  SEAT_ALREADY_HELD = "SEAT_ALREADY_HELD",
}

export default ShowErrorCode;
